# 1 is suitable for how many task, otherwise 0

OBJECT_FOR_COUNTING_TASK = {
	"people"              : 0,
	"students"            : 0,
	"geese"               : 0,
	"zebra"               : 1,
	"spectators"          : 0,
	"bushes"              : 0,
	"stairs"              : 0,
	"policeman"           : 1,
	"towels"              : 0,
	"children"            : 0,
	"boxes"               : 0,
	"goats"               : 0,
	"soldiers"            : 0,
	"books"               : 0,
	"steps"               : 0,
	"cars"                : 0,
	"sheep"               : 1,
	"flowers"             : 0,
	"windows"             : 0,
	"blankets"            : 0,
	"chair"               : 1,
	"dogs"                : 0,
	"ducks"               : 0,
	"weeds"               : 0,
	"frisbee"             : 1,
	"toaster"             : 1,
	"trees"               : 0,
	"players"             : 0,
	"pillows"             : 0,
	"remote control"      : 1,
	"glasses"             : 0,
	"bookshelf"           : 1,
	"tree branches"       : 0,
	"shoes"               : 0,
	"orange"              : 1,
	"doorway"             : 1,
	"hats"                : 0,
	"person"              : 1,
	"eagle"               : 1,
	"sneakers"            : 0,
	"computer"            : 1,
	"horses"              : 0,
	"magazines"           : 0,
	"student"             : 1,
	"olives"              : 0,
	"door"                : 1,
	"train tracks"        : 0,
	"boots"               : 0,
	"room"                : 0,
	"seat"                : 1,
	"numbers"             : 0,
	"buildings"           : 0,
	"t-shirt"             : 1,
	"book"                : 1,
	"fire hydrant"        : 1,
	"boats"               : 0,
	"drawer"              : 1,
	"towel"               : 1,
	"bottle"              : 1,
	"cell phone"          : 1,
	"mountains"           : 0,
	"kite"                : 1,
	"words"               : 0,
	"cow"                 : 1,
	"leaves"              : 0,
	"bleachers"           : 0,
	"surfer"              : 1,
	"palm tree"           : 1,
	"light fixture"       : 1,
	"socks"               : 0,
	"apartment"           : 0,
	"window"              : 1,
	"pillars"             : 0,
	"house"               : 1,
	"gloves"              : 0,
	"skis"                : 0,
	"bus"                 : 1,
	"toiletries"          : 0,
	"table"               : 1,
	"power lines"         : 0,
	"shirt"               : 1,
	"feathers"            : 0,
	"skateboard"          : 1,
	"traffic light"       : 1,
	"letters"             : 0,
	"cabinets"            : 0,
	"dog"                 : 1,
	"branches"            : 0,
	"shorts"              : 1,
	"bus stop"            : 1,
	"street light"        : 1,
	"box"                 : 1,
	"hotel"               : 0,
	"lamp"                : 1,
	"papers"              : 0,
	"bookcase"            : 1,
	"puddle"              : 1,
	"bathroom"            : 0,
	"knee pads"           : 0,
	"machine"             : 1,
	"water bottle"        : 1,
	"cat"                 : 1,
	"statue"              : 1,
	"desk"                : 1,
	"projector"           : 1,
	"living room"         : 0,
	"stop sign"           : 1,
	"stove"               : 1,
	"bike"                : 1,
	"entertainment center": 0,
	"plants"              : 0,
	"vase"                : 1,
	"hilltop"             : 0,
	"pitcher"             : 1,
	"vegetables"          : 0,
	"television"          : 1,
	"underwear"           : 1,
	"wristband"           : 1,
	"license plate"       : 1,
	"restaurant"          : 0,
	"train car"           : 1,
	"pants"               : 1,
	"floor"               : 0,
	"laptop"              : 1,
	"child"               : 1,
	"woman"               : 1,
	"bicycle"             : 1,
	"tree"                : 1,
	"bat"                 : 1,
	"hat"                 : 1,
	"wine bottle"         : 1,
	"blender"             : 1,
	"jeans"               : 1,
	"parking meter"       : 1,
	"boy"                 : 1,
	"spoon"               : 1,
	"soccer ball"         : 1,
	"surfboard"           : 1,
	"cones"               : 0,
	"sweater"             : 1,
	"word"                : 0,
	"clothes"             : 0,
	"road"                : 0,
	"car"                 : 1,
	"robot"               : 1,
	"crosswalk"           : 0,
	"arrow"               : 1,
	"telephone pole"      : 1,
	"museum"              : 0,
	"ears"                : 0,
	"straw"               : 1,
	"letter"              : 0,
	"bag"                 : 1,
	"duck"                : 1,
	"coffee cup"          : 1,
	"coffee table"        : 1,
	"hills"               : 0,
	"eyes"                : 0,
	"tank top"            : 1,
	"catcher"             : 1,
	"airplane"            : 1,
	"player"              : 1,
	"tent"                : 1,
	"power line"          : 1,
	"number"              : 0,
	"rocks"               : 0,
	"kitchen"             : 0,
	"toilet"              : 0,
	"shelf"               : 1,
	"sign post"           : 1,
	"jacket"              : 1,
	"tree trunk"          : 1,
	"girl"                : 1,
	"ear"                 : 0,
	"bed"                 : 1,
	"container"           : 1,
	"snowboard"           : 1,
	"entrance"            : 0,
	"planter"             : 1,
	"hair"                : 0,
	"pockets"             : 0,
	"refrigerator"        : 1,
	"motorcycle"          : 1,
	"nose"                : 0,
	"street"              : 0,
	"airport"             : 0,
	"tags"                : 0,
	"flower"              : 0,
	"sun"                 : 0,
	"building"            : 0,
	"fork"                : 1,
	"eye"                 : 0,
	"blinds"              : 0,
	"river"               : 0,
	"animal"              : 1,
	"dish"                : 0,
	"shop"                : 0,
	"flip flop"           : 1,
	"classroom"           : 0,
	"hillside"            : 0,
	"cabinet door"        : 1,
	"eye glasses"         : 0,
	"boat"                : 1,
	"parking lot"         : 0,
	"couple"              : 0,
	"outfit"              : 0,
	"pot"                 : 1,
	"propeller"           : 1,
	"wheels"              : 0,
	"glass"               : 0,
	"wires"               : 0,
	"cup"                 : 1,
	"head"                : 0,
	"cabinet"             : 1,
	"drawings"            : 0,
	"branch"              : 0,
	"waterfall"           : 0,
	"outlet"              : 0,
	"tree branch"         : 0,
	"pillow"              : 1,
	"bench"               : 1,
	"umbrella"            : 1,
	"flags"               : 0,
	"skier"               : 0,
	"figurine"            : 0,
	"can"                 : 1,
	"guy"                 : 1,
	"bush"                : 1,
	"horse"               : 1,
	"lock"                : 0,
	"necklace"            : 1,
	"leaf"                : 0,
	"legs"                : 0,
	"faucet"              : 0,
	"lamb"                : 1,
	"van"                 : 1,
	"picture"             : 1,
	"lamp shade"          : 0,
	"heater"              : 1,
	"island"              : 0,
	"mouth"               : 0,
	"garden"              : 0,
	"soap"                : 1,
	"ball"                : 1,
	"leg"                 : 0,
	"artwork"             : 1,
	"card"                : 1,
	"runway"              : 0,
	"camera"              : 1,
	"toilet seat"         : 1,
	"tower"               : 1,
	"phone"               : 0,
	"blanket"             : 0,
	"plant"               : 0,
	"town"                : 0,
	"burner"              : 1,
	"office"              : 0,
	"beach"               : 0,
	"hands"               : 0,
	"microwave"           : 1,
	"man"                 : 1,
	"alien"               : 1,
	"stick"               : 1,
	"arm"                 : 0,
	"oven"                : 1,
	"robe"                : 1,
	"basket"              : 1,
	"farm"                : 0,
	"ottoman"             : 0,
	"feet"                : 0,
	"sail"                : 1,
	"park"                : 0,
	"name tag"            : 1,
	"mirror"              : 1,
	"intersection"        : 0,
	"couch"               : 1,
	"sand"                : 0,
	"cane"                : 1,
	"city"                : 0,
	"home plate"          : 1,
	"bowl"                : 1,
	"face"                : 0,
	"graffiti"            : 1,
	"pocket"              : 1,
	"device"              : 1,
	"dispenser"           : 1,
	"driver"              : 1,
	"magnets"             : 0,
	"curtain"             : 1,
	"bucket"              : 1,
	"shelter"             : 1,
	"coat"                : 1,
	"paper"               : 0,
	"family"              : 0,
	"hand"                : 0,
	"cone"                : 1,
	"backpack"            : 1,
	"keyboard"            : 1,
	"wetsuit"             : 1,
	"candle"              : 1,
	"mountain"            : 0,
	"bull"                : 1,
	"wheel"               : 1,
	"bathtub"             : 1,
	"rug"                 : 1,
	"apron"               : 1,
	"waist"               : 0,
	"helmet"              : 1,
	"balcony"             : 0,
	"hill"                : 0,
	"umpire"              : 1,
	"tag"                 : 0,
	"path"                : 0,
	"truck"               : 1,
	"wing"                : 0,
	"screen"              : 1,
	"neck"                : 0,
	"sink"                : 1,
	"cliff"               : 0,
	"bear"                : 1,
	"boot"                : 0,
	"bridge"              : 1,
	"mask"                : 1,
	"sidewalk"            : 0,
	"coach"               : 1,
	"cart"                : 1,
	"frame"               : 0,
	"lid"                 : 0,
	"label"               : 0,
	"dome"                : 0,
	"mat"                 : 0,
	"gun"                 : 1,
	"stadium"             : 0,
	"pan"                 : 1,
	"monitor"             : 1,
	"plate"               : 1,
	"gate"                : 0,
	"clock"               : 1,
	"buoy"                : 1,
	"suit"                : 1,
	"clouds"              : 0,
	"post"                : 1,
	"monster"             : 1,
	"toilet tank"         : 1,
	"railroad"            : 0,
	"walls"               : 0,
	"roadway"             : 0,
	"display"             : 0,
	"platform"            : 0,
	"cross"               : 0,
	"foot"                : 0,
	"obstacle"            : 1,
	"symbol"              : 0,
	"jersey"              : 1,
	"sign"                : 1,
	"sky"                 : 0,
	"windshield"          : 1,
	"trunk"               : 1,
	"collar"              : 1,
	"vest"                : 0,
	"horn"                : 1,
	"pole"                : 1,
	"roof"                : 1,
	"crane"               : 1,
	"walkway"             : 0,
	"jet"                 : 1,
	"fence"               : 0,
	"tape"                : 1,
	"tie"                 : 1,
	"glove"               : 1,
	"uniform"             : 1,
	"bell"                : 1,
	"cap"                 : 1,
	"tires"               : 0,
	"lawn"                : 0,
	"trailer"             : 1,
	"deck"                : 0,
	"plain"               : 0,
	"tail"                : 1,
	"pipe"                : 1,
	"barn"                : 0,
	"shore"               : 0,
	"counter"             : 0,
	"field"               : 0,
	"flag"                : 1,
	"logo"                : 1,
	"countertop"          : 1,
	"beak"                : 0,
	"log"                 : 1,
	"train"               : 1,
	"baseball"            : 1,
	"beard"               : 0,
	"chain"               : 1,
	"dock"                : 1,
	"belt"                : 1,
	"drain"               : 1,
	"paint"               : 0,
	"cord"                : 1,
	"pavement"            : 0,
	"shoe"                : 0,
	"crowd"               : 0,
	"ceiling"             : 0,
	"heart"               : 0,
	"wire"                : 1,
	"watch"               : 1,
	"wrist"               : 0,
	"dirt"                : 0,
	"grass"               : 0,
	"tire"                : 1,
	"ocean"               : 0,
	"wall"                : 0,
	"cable"               : 1,
	"wine"                : 1,
	"cloud"               : 0,
	"rope"                : 1,
	"rock"                : 1,
	"mud"                 : 0,
	"mane"                : 0,
	"ground"              : 0,
	"gravel"              : 0,
	"ice"                 : 0,
	"air"                 : 0,
	"food"                : 0,
	"snow"                : 0,
	"seaweed"             : 0,
	"fog"                 : 0,
	"tissue"              : 0,
	"water"               : 0,
	"fur"                 : 0,
	"guests"              : 0,
	"mangoes"             : 0,
	"chairs"              : 0,
	"chocolate chips"     : 0,
	"cookies"             : 0,
	"apples"              : 0,
	"donuts"              : 0,
	"oranges"             : 0,
	"pens"                : 0,
	"stars"               : 0,
	"pears"               : 0,
	"carrots"             : 0,
	"roses"               : 0,
	"mugs"                : 0,
	"cell phones"         : 0,
	"cherries"            : 0,
	"policemen"           : 0,
	"candies"             : 0,
	"pandas"              : 0,
	"pencils"             : 0,
	"ice cubes"           : 0,
	"seagulls"            : 0,
	"melons"              : 0,
	"raisins"             : 0,
	"crates"              : 0,
	"meatballs"           : 0,
	"antelope"            : 1,
	"tomatoes"            : 0,
	"muffins"             : 0,
	"shirts"              : 0,
	"watermelons"         : 0,
	"hot dogs"            : 0,
	"jars"                : 0,
	"cupcakes"            : 0,
	"pepperoni"           : 1,
	"strawberries"        : 0,
	"berries"             : 0,
	"grapes"              : 0,
	"cows"                : 0,
	"pine trees"          : 0,
	"televisions"         : 0,
	"raisin"              : 1,
	"tangerine"           : 1,
	"deer"                : 1,
	"bananas"             : 0,
	"laptops"             : 0,
	"biscuits"            : 0,
	"vases"               : 0,
	"zebras"              : 0,
	"soda cans"           : 0,
	"moose"               : 1,
	"toothbrushes"        : 0,
	"chickens"            : 0,
	"blossoms"            : 0,
	"sunflowers"          : 0,
	"antelopes"           : 0,
	"polar bear"          : 1,
	"pomegranate"         : 1,
	"remote controls"     : 0,
	"pigeons"             : 0,
	"wine glasses"        : 0,
	"panda bears"         : 0,
	"kittens"             : 0,
	"sugar packets"       : 0,
	"drawers"             : 0,
	"bicycles"            : 0,
	"oreo"                : 1,
	"wine bottles"        : 0,
	"lamps"               : 0,
	"rhinos"              : 0,
	"lemons"              : 0,
	"lilies"              : 0,
	"beans"               : 0,
	"bottles"             : 0,
	"elephants"           : 0,
	"potatoes"            : 0,
	"bikes"               : 0,
	"salmon"              : 1,
	"peppers"             : 0,
	"peaches"             : 0,
	"washing machine"     : 1,
	"water bottles"       : 0,
	"hotel room"          : 0,
	"pretzels"            : 0,
	"almonds"             : 0,
	"computers"           : 0,
	"bar stools"          : 0,
	"lions"               : 0,
	"swans"               : 0,
	"paper towels"        : 0,
	"beds"                : 0,
	"peas"                : 0,
	"pistachio"           : 1,
	"bison"               : 1,
	"cheetah"             : 1,
	"cucumbers"           : 0,
	"shoppers"            : 0,
	"sharks"              : 0,
	"pizza slices"        : 0,
	"pigs"                : 0,
	"blenders"            : 0,
	"fries"               : 0,
	"eagles"              : 0,
	"hibiscus"            : 0,
	"teddy bears"         : 0,
	"dumplings"           : 0,
	"crackers"            : 0,
	"wolves"              : 0,
	"panda bear"          : 1,
	"twigs"               : 0,
	"hippos"              : 0,
	"monkeys"             : 0,
	"mice"                : 0,
	"tourists"            : 0,
	"raspberries"         : 0,
	"bookshelves"         : 0,
	"farmers"             : 0,
	"donkeys"             : 0,
	"chickpeas"           : 0,
	"macaroni"            : 1,
	"taco"                : 1,
	"boar"                : 1,
	"video games"         : 0,
	"noodles"             : 0,
	"dolphins"            : 0,
	"beer cans"           : 0,
	"kangaroo"            : 1,
	"pumpkins"            : 0,
	"suitcases"           : 0,
	"brownies"            : 0,
	"fisherman"           : 1,
	"spoons"              : 0,
	"apple"               : 1,
	"cans"                : 0,
	"cranberries"         : 0,
	"cats"                : 0,
	"umbrellas"           : 0,
	"crumbs"              : 0,
	"ostrich"             : 1,
	"oak tree"            : 1,
	"taxis"               : 0,
	"ostriches"           : 0,
	"hamburgers"          : 0,
	"daisy"               : 1,
	"toys"                : 0,
	"passengers"          : 0,
	"orchids"             : 0,
	"bats"                : 0,
	"penguins"            : 0,
	"houses"              : 0,
	"napkins"             : 0,
	"pickles"             : 0,
	"pear"                : 1,
	"cookie"              : 1,
	"buns"                : 0,
	"peach"               : 1,
	"jackets"             : 0,
	"candle holder"       : 1,
	"ice cube"            : 1,
	"soccer balls"        : 0,
	"bagels"              : 0,
	"skyscrapers"         : 0,
	"stuffed bears"       : 0,
	"mashed potatoes"     : 0,
	"fingers"             : 0,
	"blackberries"        : 0,
	"shrimp"              : 1,
	"sailboats"           : 0,
	"tables"              : 0,
	"hippo"               : 1,
	"gorilla"             : 1,
	"donut"               : 1,
	"croissants"          : 0,
	"printers"            : 0,
	"pikachu"             : 1,
	"bricks"              : 0,
	"dishes"              : 0,
	"dvd players"         : 0,
	"vending machine"     : 1,
	"balloons"            : 0,
	"pigeon"              : 1,
	"pots"                : 0,
	"flamingo"            : 1,
	"walnuts"             : 0,
	"blueberries"         : 0,
	"pastries"            : 0,
	"pedestrians"         : 0,
	"teddy bear"          : 1,
	"owls"                : 0,
	"banana bunches"      : 0,
	"calf"                : 1,
	"silverware"          : 1,
	"buses"               : 0,
	"light bulbs"         : 0,
	"anchovies"           : 0,
	"pine tree"           : 1,
	"octopus"             : 1,
	"waffles"             : 0,
	"palm trees"          : 0,
	"amusement park"      : 0,
	"fire extinguisher"   : 1,
	"skateboards"         : 0,
	"chicken"             : 1,
	"motorcycles"         : 0,
	"cactus"              : 1,
	"shampoo bottle"      : 1,
	"stickers"            : 0,
	"dresses"             : 0,
	"doors"               : 0,
	"sandwiches"          : 0,
	"dolls"               : 0,
	"kites"               : 0,
	"bandage"             : 1,
	"blueberry"           : 1,
	"fish"                : 1,
	"couches"             : 0,
	"restaurants"         : 0,
	"scooters"            : 0,
	"chopsticks"          : 0,
	"ribs"                : 0,
	"flower pot"          : 1,
	"sticky notes"        : 0,
	"giraffe"             : 1,
	"banana"              : 1,
	"avocados"            : 0,
	"pancakes"            : 0,
	"ice-cream cone"      : 1,
	"tennis balls"        : 0,
	"potato chips"        : 0,
	"beads"               : 0,
	"lily"                : 1,
	"ravioli"             : 1,
	"panda"               : 1,
	"rhino"               : 1,
	"artichokes"          : 0,
	"apartment building"  : 0,
	"food trucks"         : 0,
	"fire trucks"         : 0,
	"swan"                : 1,
	"tiger"               : 1,
	"melon"               : 1,
	"plantains"           : 0,
	"sugar packet"        : 1,
	"bags"                : 0,
	"snakes"              : 0,
	"sweet potatoes"      : 0,
	"rice"                : 0,
	"coconuts"            : 0,
	"skyscraper"          : 0,
	"pineapples"          : 0,
	"gas station"         : 1,
	"officers"            : 0,
	"picnic tables"       : 0,
	"butterflies"         : 0,
	"bedroom"             : 0,
	"snow flakes"         : 0,
	"cards"               : 0,
	"mango"               : 1,
	"donkey"              : 1,
	"onions"              : 0,
	"spices"              : 0,
	"coffee cups"         : 0,
	"zucchini"            : 1,
	"armchair"            : 1,
	"boys"                : 0,
	"toy car"             : 1,
	"papaya"              : 1,
	"tractors"            : 0,
	"giraffes"            : 0,
	"utensils"            : 0,
	"surfboards"          : 0,
	"asparagus"           : 0,
	"street lights"       : 0,
	"coffee maker"        : 1,
	"jeep"                : 1,
	"egg white"           : 1,
	"monkey"              : 1,
	"toy"                 : 1,
	"birds"               : 0,
	"baseball players"    : 0,
	"life jackets"        : 0,
	"pretzel"             : 1,
	"peacock"             : 1,
	"cakes"               : 0,
	"tuna"                : 1,
	"kiwis"               : 0,
	"candles"             : 0,
	"stuffed animals"     : 0,
	"visitors"            : 0,
	"cranberry"           : 1,
	"girls"               : 0,
	"sausages"            : 0,
	"alligator"           : 1,
	"urinal"              : 1,
	"beets"               : 0,
	"pizza shop"          : 1,
	"wildflowers"         : 0,
	"canisters"           : 0,
	"tourist"             : 1,
	"butter knife"        : 1,
	"lambs"               : 0,
	"shelves"             : 0,
	"tents"               : 0,
	"waitress"            : 1,
	"dragonfly"           : 1,
	"carrot"              : 1,
	"pans"                : 0,
	"trays"               : 0,
	"soda bottle"         : 1,
	"mickey mouse"        : 1,
	"lobster"             : 1,
	"beach chair"         : 1,
	"homes"               : 0,
	"cash register"       : 1,
	"bugs"                : 0,
	"lego"                : 1,
	"kitten"              : 1,
	"cheese cube"         : 1,
	"desktop computer"    : 1,
	"seagull"             : 1,
	"life preserver"      : 1,
	"pizzas"              : 0,
	"chess piece"         : 1,
	"parrots"             : 0,
	"sandals"             : 0,
	"benches"             : 0,
	"nightstands"         : 0,
	"owl"                 : 1,
	"angry bird"          : 1,
	"hot dog"             : 1,
	"wii controllers"     : 0,
	"frog"                : 1,
	"ladles"              : 1,
	"elmo"                : 0,
	"biscuit"             : 1,
	"star"                : 1,
	"lizard"              : 1,
	"watermelon"          : 1,
	"bagel"               : 1,
	"bears"               : 0,
	"coffee beans"        : 0,
	"shopper"             : 1,
	"phones"              : 0,
	"traffic lights"      : 0,
	"office chair"        : 1,
	"rackets"             : 0,
	"paper container"     : 1,
	"pliers"              : 1,
	"onion rings"         : 1,
	"canoe"               : 1,
	"shops"               : 0,
	"gummy bear"          : 1,
	"workers"             : 0,
	"necklaces"           : 0,
	"helmets"             : 0,
	"pig"                 : 1,
	"packages"            : 0,
	"snowboards"          : 0,
	"beach umbrella"      : 1,
	"lion"                : 1,
	"action figure"       : 1,
	"bee"                 : 1,
	"pills"               : 0,
	"crab"                : 1,
	"poodle"              : 1,
	"ornaments"           : 0,
	"chicken breast"      : 1,
	"soap bottle"         : 1,
	"burger"              : 1,
	"cups"                : 0,
	"brownie"             : 1,
	"ramekin"             : 1,
	"vehicles"            : 0,
	"airplanes"           : 0,
	"parsley"             : 1,
	"fire truck"          : 1,
	"marshmallow"         : 1,
	"women"               : 0,
	"forks"               : 1,
	"cupcake"             : 1,
	"kimono"              : 1,
	"beetle"              : 1,
	"can opener"          : 1,
	"tennis ball"         : 1,
	"electric toothbrush" : 1,
	"computer mouse"      : 1,
	"muffin"              : 1,
	"kiwi"                : 1,
	"nuts"                : 0,
	"skateboarder"        : 1,
	"broccoli"            : 1,
	"fruits"              : 0,
	"basil"               : 1,
	"knives"              : 0,
	"stapler"             : 1,
	"leopard"             : 1,
	"mug"                 : 1,
	"beer bottle"         : 1,
	"burrito"             : 1,
	"roast beef"          : 1,
	"shopping center"     : 1,
	"seeds"               : 0,
	"alarm clock"         : 1,
	"castles"             : 0,
	"baskets"             : 0,
	"artichoke"           : 1,
	"bikini"              : 1,
	"cheeseburger"        : 1,
	"egg yolk"            : 1,
	"guys"                : 0,
	"penguin"             : 1,
	"sticks"              : 0,
	"containers"          : 0,
	"binder"              : 1,
	"strawberry"          : 1,
	"soft drink"          : 1,
	"lettuce"             : 1,
	"gas pump"            : 1,
	"flip flops"          : 0,
	"bunny"               : 1,
	"hairbrush"           : 1,
	"pizza boxes"         : 0,
	"lighthouse"          : 1,
	"croissant"           : 1,
	"outlets"             : 0,
	"bus driver"          : 1,
	"sheets"              : 0,
	"customers"           : 0,
	"omelette"            : 1,
	"dolphin"             : 1,
	"jar"                 : 1,
	"stuffed bear"        : 1,
	"cupboards"           : 0,
	"sweet potato"        : 1,
	"soap dispensers"     : 0,
	"spots"               : 0,
	"logs"                : 0,
	"ski lift"            : 1,
	"cowboy"              : 1,
	"employee"            : 1,
	"coke"                : 1,
	"ovens"               : 0,
	"ham"                 : 1,
	"celery"              : 1,
	"raspberry"           : 1,
	"fans"                : 0,
	"trucks"              : 0,
	"scissors"            : 1,
	"sticker"             : 1,
	"baseball bats"       : 0,
	"soldier"             : 1,
	"pajamas"             : 0,
	"wolf"                : 1,
	"mannequins"          : 0,
	"grapefruit"          : 0,
	"camel"               : 1,
	"piano"               : 1,
	"outfits"             : 0,
	"video game"          : 1,
	"toaster oven"        : 1,
	"coffee shop"         : 1,
	"christmas lights"    : 0,
	"calculator"          : 1,
	"tiles"               : 0,
	"bird house"          : 1,
	"balloon"             : 1,
	"tea kettle"          : 1,
	"balls"               : 0,
	"bowls"               : 0,
	"onion ring"          : 1,
	"monitors"            : 0,
	"pizza"               : 1,
	"clocks"              : 0,
	"mattresses"          : 0,
	"paintings"           : 0,
	"soda can"            : 1,
	"backpacks"           : 0,
	"zoo"                 : 1,
	"salt shaker"         : 1,
	"wii game"            : 1,
	"figurines"           : 0,
	"shopping bag"        : 1,
	"dvd player"          : 1,
	"flatbread"           : 1,
	"sailboat"            : 1,
	"pencil"              : 1,
	"peanuts"             : 0,
	"napkin"              : 1,
	"men"                 : 0,
	"waiter"              : 1,
	"mountain peak"       : 1,
	"vitamins"            : 0,
	"snow boots"          : 0,
	"air conditioner"     : 1,
	"cabinet doors"       : 0,
	"suitcase"            : 1,
	"gourd"               : 1,
	"eggplant"            : 1,
	"paper dispenser"     : 1,
	"soccer player"       : 1,
	"leggings"            : 0,
	"bubbles"             : 0,
	"swimming pool"       : 1,
	"table lamp"          : 1,
	"mushrooms"           : 0,
	"cooking pot"         : 1,
	"match"               : 1,
	"coffee pot"          : 1,
	"taxi"                : 1,
	"light bulb"          : 1,
	"stuffed dog"         : 1,
	"coffee mug"          : 1,
	"cloths"              : 0,
	"cookie jar"          : 1,
	"blouse"              : 1,
	"spatula"             : 1,
	"light switch"        : 1,
	"tongs"               : 0,
	"stores"              : 0,
	"sweatshirt"          : 1,
	"baking pan"          : 1,
	"lemonade"            : 1,
	"toothpicks"          : 0,
	"pecan"               : 1,
	"cowboy hat"          : 1,
	"hammer"              : 1,
	"cooking utensils"    : 0,
	"hair clip"           : 1,
	"carts"               : 0,
	"cookbook"            : 1,
	"riding boots"        : 0,
	"pizza slice"         : 1,
	"tofu"                : 1,
	"cherry"              : 1,
	"tea pot"             : 1,
	"vines"               : 0,
	"tomato"              : 1,
	"snowboarder"         : 1,
	"stuffed animal"      : 1,
	"skate park"          : 1,
	"polo shirt"          : 1,
	"train station"       : 1,
	"potato"              : 1,
	"chopstick"           : 1,
	"snoopy"              : 1,
	"bracelets"           : 0,
	"office supplies"     : 0,
	"finger"              : 1,
	"cereal box"          : 1,
	"pasta"               : 1,
	"notepad"             : 1,
	"dress shirt"         : 1,
	"eggs"                : 0,
	"raincoat"            : 1,
	"canister"            : 1,
	"spray can"           : 1,
	"desk lamp"           : 1,
	"meadow"              : 1,
	"hair dryer"          : 1,
	"milk carton"         : 1,
	"dining table"        : 1,
	"skater"              : 1,
	"banana bunch"        : 1,
	"paper towel"         : 1,
	"wok"                 : 1,
	"cinnamon roll"       : 1,
	"water glass"         : 0,
	"pillowcase"          : 1,
	"parachutes"          : 0,
	"saucer"              : 1,
	"beet"                : 1,
	"hotdog bun"          : 1,
	"toothbrush"          : 1,
	"mannequin"           : 1,
	"keyboards"           : 0,
	"coconut"             : 1,
	"pea"                 : 1,
	"pedestrian"          : 1,
	"school"              : 0,
	"pepper shaker"       : 1,
	"earphones"           : 0,
	"rubber duck"         : 1,
	"dream catcher"       : 1,
	"baked goods"         : 0,
	"bedspread"           : 1,
	"package"             : 1,
	"chili"               : 1,
	"pepper"              : 1,
	"avocado"             : 1,
	"swimsuit"            : 1,
	"wii"                 : 1,
	"rice cooker"         : 1,
	"food processor"      : 1,
	"elephant"            : 1,
	"lemon"               : 1,
	"lunch box"           : 1,
	"trash can"           : 1,
	"speakers"            : 0,
	"cotton dessert"      : 1,
	"headband"            : 1,
	"tortilla"            : 1,
	"cauliflower"         : 1,
	"ipod"                : 1,
	"hospital"            : 0,
	"sock"                : 1,
	"rabbit"              : 1,
	"goggles"             : 1,
	"pineapple"           : 1,
	"egg roll"            : 1,
	"cutting board"       : 1,
	"gas stove"           : 1,
	"cake"                : 1,
	"plates"              : 0,
	"waffle"              : 1,
	"cabbage"             : 1,
	"ambulance"           : 1,
	"cds"                 : 0,
	"step"                : 1,
	"baked good"          : 1,
	"desserts"            : 0,
	"goat"                : 1,
	"folding chair"       : 1,
	"appetizers"          : 0,
	"doll"                : 1,
	"mixing bowl"         : 1,
	"wii controller"      : 1,
	"french toast"        : 1,
	"school bus"          : 1,
	"microwave oven"      : 1,
	"street sign"         : 1,
	"tools"               : 0,
	"vests"               : 0,
	"broom"               : 1,
	"traffic sign"        : 1,
	"earring"             : 1,
	"visitor"             : 1,
	"herbs"               : 0,
	"beer mug"            : 1,
	"boulders"            : 0,
	"grape"               : 1,
	"snow shoes"          : 1,
	"walnut"              : 1,
	"worker"              : 1,
	"pumpkin"             : 1,
	"bottle cap"          : 1,
	"batteries"           : 0,
	"berry"               : 1,
	"parking sign"        : 1,
	"shark"               : 1,
	"officer"             : 1,
	"bar stool"           : 1,
	"pond"                : 1,
	"cameras"             : 0,
	"placemat"            : 1,
	"customer"            : 1,
	"dining room"         : 0,
	"clock tower"         : 1,
	"picture frame"       : 1,
	"uniforms"            : 0,
	"aircraft"            : 1,
	"briefcase"           : 1,
	"pen"                 : 1,
	"dresser"             : 1,
	"rose"                : 1,
	"sprinkles"           : 0,
	"spectator"           : 1,
	"hedges"              : 0,
	"suv"                 : 1,
	"games"               : 0,
	"pancake"             : 1,
	"cyclist"             : 1,
	"puppy"               : 1,
	"towel dispenser"     : 1,
	"ketchup bottle"      : 1,
	"pizza oven"          : 1,
	"toilet paper"        : 1,
	"side table"          : 1,
	"pizza crust"         : 1,
	"handbag"             : 1,
	"manhole cover"       : 1,
	"thumb"               : 1,
	"suits"               : 1,
	"steak"               : 1,
	"orchard"             : 1,
	"masks"               : 0,
	"dress"               : 1,
	"swimmer"             : 1,
	"sunflower"           : 1,
	"parrot"              : 1,
	"almond"              : 1,
	"tree leaves"         : 0,
	"candy"               : 1,
	"dvds"                : 0,
	"storage box"         : 1,
	"chalkboard"          : 1,
	"spider"              : 1,
	"trash bag"           : 1,
	"floor lamp"          : 1,
	"undershirt"          : 1,
	"luggage"             : 1,
	"snail"               : 1,
	"racket"              : 1,
	"mirrors"             : 0,
	"crate"               : 1,
	"curtains"            : 0,
	"auditorium"          : 1,
	"towers"              : 0,
	"tablecloth"          : 1,
	"milkshake"           : 1,
	"paws"                : 0,
	"turkey"              : 1,
	"trains"              : 0,
	"cages"               : 0,
	"factory"             : 1,
	"costume"             : 1,
	"fountain"            : 1,
	"butterfly"           : 1,
	"bartender"           : 1,
	"paint brush"         : 1,
	"pizza pie"           : 1,
	"groceries"           : 0,
	"passenger"           : 1,
	"supermarket"         : 1,
	"end table"           : 1,
	"radio"               : 1,
	"squirrel"            : 1,
	"hamburger"           : 1,
	"twig"                : 1,
	"dishwasher"          : 1,
	"orchid"              : 1,
	"cafeteria"           : 1,
	"wildflower"          : 1,
	"stroller"            : 1,
	"bun"                 : 1,
	"ingredient"          : 0,
	"squash"              : 1,
	"ear buds"            : 0,
	"cappuccino"          : 1,
	"toddler"             : 1,
	"magazine"            : 1,
	"beer can"            : 1,
	"baking sheet"        : 1,
	"bird"                : 1,
	"shopping cart"       : 1,
	"scooter"             : 1,
	"hangar"              : 1,
	"baseball mitt"       : 1,
	"church"              : 1,
	"trunks"              : 0,
	"thermometer"         : 1,
	"performer"           : 1,
	"nightstand"          : 1,
	"cabin"               : 1,
	"fireplace"           : 1,
	"utensil"             : 1,
	"dry-erase board"     : 1,
	"spray bottle"        : 1,
	"snow pants"          : 1,
	"chef hat"            : 1,
	"popcorn"             : 1,
	"highway"             : 0,
	"dragons"             : 0,
	"blossom"             : 1,
	"hand soap"           : 1,
	"kitchen towel"       : 1,
	"decorations"         : 0,
	"cathedral"           : 1,
	"mustache"            : 1,
	"snake"               : 1,
	"garlic"              : 1,
	"picnic table"        : 1,
	"baker"               : 0,
	"printer"             : 0,
	"cooking utensil"     : 0,
	"notebook"            : 0,
	"food container"      : 0,
	"wine glass"          : 0,
	"vendors"             : 0,
	"cucumber"            : 1,
	"coffee bean"         : 0,
	"gentleman"           : 0,
	"drapes"              : 0,
	"food truck"          : 1,
	"cheesecake"          : 1,
	"entree"              : 1,
	"granola"             : 1,
	"lady"                : 1,
	"bandana"             : 1,
	"sunglasses"          : 0,
	"goose"               : 1,
	"buoys"               : 0,
	"bird cage"           : 1,
	"drinks"              : 0,
	"animals"             : 0,
	"vehicle"             : 1,
	"price tag"           : 1,
	"loaf"                : 1,
	"restroom"            : 0,
	"wheelchair"          : 1,
	"ropes"               : 0,
	"cooker"              : 1,
	"lime"                : 1,
	"soap dish"           : 1,
	"biker"               : 1,
	"tv stand"            : 1,
	"toppings"            : 0,
	"garage door"         : 1,
	"knife"               : 1,
	"sconce"              : 1,
	"cigarette"           : 1,
	"painting"            : 1,
	"bread loaf"          : 1,
	"castle"              : 1,
	"game controller"     : 1,
	"photographer"        : 1,
	"christmas light"     : 1,
	"newspaper"           : 1,
	"scrub brush"         : 1,
	"pita"                : 1,
	"sushi"               : 1,
	"characters"          : 0,
	"comforter"           : 1,
	"eiffel tower"        : 1,
	"mound"               : 1,
	"computer desk"       : 1,
	"coats"               : 0,
	"sofa"                : 1,
	"helicopter"          : 1,
	"farmer"              : 1,
	"video camera"        : 1,
	"bug"                 : 1,
	"packet"              : 1,
	"bell tower"          : 0,
	"sporting equipment"  : 1,
	"jumpsuit"            : 1,
	"garland"             : 1,
	"minivan"             : 1,
	"whale"               : 1,
	"toothpaste"          : 1,
	"feta cheese"         : 1,
	"pizza box"           : 1,
	"shampoo"             : 1,
	"skirt"               : 1,
	"goal"                : 0,
	"fruit"               : 0,
	"life jacket"         : 1,
	"wallet"              : 1,
	"dish drainer"        : 1,
	"toilet brush"        : 1,
	"egg"                 : 1,
	"hose"                : 1,
	"turbines"            : 0,
	"seed"                : 0,
	"cookie dough"        : 1,
	"fishing pole"        : 1,
	"toilet bowl"         : 1,
	"tissue box"          : 1,
	"locomotive"          : 1,
	"sausage"             : 1,
	"grater"              : 1,
	"dugout"              : 1,
	"tray"                : 1,
	"gadget"              : 1,
	"window frame"        : 1,
	"whipped cream"       : 1,
	"blazer"              : 1,
	"juice box"           : 1,
	"athlete"             : 1,
	"smoke stack"         : 1,
	"closet"              : 1,
	"gifts"               : 0,
	"rooftop"             : 0,
	"serving dish"        : 1,
	"cracker"             : 1,
	"pie"                 : 1,
	"pastry"              : 1,
	"control panel"       : 1,
	"soap dispenser"      : 1,
	"piercing"            : 1,
	"toilet lid"          : 1,
	"shower door"         : 1,
	"store"               : 1,
	"ornament"            : 1,
	"moon"                : 1,
	"parachute"           : 1,
	"menus"               : 1,
	"cupboard"            : 1,
	"nut"                 : 1,
	"gown"                : 1,
	"onion"               : 1,
	"pocket watch"        : 1,
	"toolbox"             : 1,
	"guitar"              : 1,
	"fan"                 : 1,
	"beer"                : 1,
	"ladle"               : 1,
	"chandelier"          : 1,
	"sheet"               : 1,
	"charger"             : 1,
	"mattress"            : 1,
	"mushroom"            : 1,
	"antennas"            : 0,
	"yard"                : 1,
	"arms"                : 0,
	"ceiling light"       : 1,
	"receipt"             : 1,
	"shower curtain"      : 1,
	"toast"               : 1,
	"character"           : 0,
	"ice maker"           : 1,
	"napkin dispenser"    : 1,
	"utensil holder"      : 1,
	"palace"              : 1,
	"ginger"              : 1,
	"mustard"             : 1,
	"chef"                : 1,
	"serving tray"        : 1,
	"team"                : 0,
	"powdered sugar"      : 0,
	"shoe laces"          : 0,
	"earrings"            : 0,
	"diaper"              : 1,
	"snacks"              : 0,
	"flames"              : 0,
	"theater"             : 0,
	"forest"              : 0,
	"map"                 : 1,
	"nest"                : 1,
	"cigarettes"          : 0,
	"banana peel"         : 1,
	"salon"               : 1,
	"coffee"              : 1,
	"microphone"          : 1,
	"pilot"               : 1,
	"appliance"           : 1,
	"cockpit"             : 1,
	"mozzarella"          : 1,
	"mustard bottle"      : 1,
	"meats"               : 0,
	"pizza tray"          : 1,
	"library"             : 0,
	"ski"                 : 0,
	"vanilla"             : 0,
	"kiosk"               : 1,
	"instrument"          : 1,
	"village"             : 1,
	"cables"              : 0,
	"jockey"              : 1,
	"xbox controller"     : 1,
	"salad dressing"      : 0,
	"horns"               : 0,
	"sandwich"            : 1,
	"pizza pan"           : 1,
	"sponge"              : 1,
	"turtle"              : 1,
	"bath towel"          : 1,
	"ketchup"             : 1,
	"controllers"         : 0,
	"olive"               : 1,
	"parmesan cheese"     : 1,
	"merchandise"         : 1,
	"purse"               : 1,
	"chimney"             : 1,
	"wagon"               : 1,
	"pasta salad"         : 1,
	"father"              : 1,
	"mountain side"       : 0,
	"lunch"               : 1,
	"hand dryer"          : 1,
	"ice cream"           : 1,
	"headphones"          : 0,
	"pizza cutter"        : 1,
	"cemetery"            : 0,
	"tattoos"             : 0,
	"steering wheel"      : 1,
	"temple"              : 0,
	"soda"                : 1,
	"bracelet"            : 1,
	"cream cheese"        : 1,
	"sculpture"           : 1,
	"plier"               : 1,
	"mailbox"             : 1,
	"aquarium"            : 1,
	"bread"               : 1,
	"pipes"               : 0,
	"platter"             : 1,
	"egg carton"          : 1,
	"cords"               : 0,
	"apple logo"          : 1,
	"medicine cabinet"    : 1,
	"clock hand"          : 1,
	"peanut"              : 1,
	"antenna"             : 1,
	"sword"               : 1,
	"dish soap"           : 1,
	"lake"                : 1,
	"cereal"              : 1,
	"shoe lace"           : 1,
	"shaving cream"       : 1,
	"gift"                : 1,
	"appetizer"           : 1,
	"seat belt"           : 1,
	"yogurt"              : 1,
	"cake stand"          : 1,
	"tractor"             : 1,
	"teeth"               : 0,
	"kettle"              : 1,
	"wines"               : 0,
	"baseball bat"        : 1,
	"trumpet"             : 1,
	"garment"             : 1,
	"poster"              : 1,
	"waste basket"        : 1,
	"market"              : 0,
	"envelope"            : 1,
	"staircase"           : 1,
	"safety jacket"       : 1,
	"spinach"             : 1,
	"courtyard"           : 1,
	"cake pan"            : 1,
	"satellite dish"      : 1,
	"computer monitor"    : 1,
	"hallway"             : 0,
	"potato salad"        : 1,
	"lips"                : 0,
	"tablet"              : 1,
	"skillet"             : 1,
	"cd"                  : 1,
	"weapon"              : 1,
	"tool"                : 1,
	"son"                 : 1,
	"vendor"              : 1,
	"wardrobe"            : 1,
	"meal"                : 1,
	"bouquet"             : 1,
	"mayonnaise"          : 1,
	"olive oil"           : 0,
	"hearts"              : 0,
	"engineer"            : 1,
	"mouse pad"           : 1,
	"citrus"              : 0,
	"crown"               : 1,
	"bacon"               : 1,
	"dragon"              : 1,
	"fence post"          : 1,
	"bubble"              : 1,
	"luggage cart"        : 1,
	"cotton candy"        : 1,
	"grill"               : 1,
	"wristwatch"          : 1,
	"bakery"              : 0,
	"vegetable"           : 0,
	"beverages"           : 0,
	"ship"                : 1,
	"fruit stand"         : 1,
	"ladder"              : 1,
	"snowsuit"            : 1,
	"stir fry"            : 0,
	"caramel"             : 1,
	"coleslaw"            : 1,
	"rifle"               : 1,
	"bread box"           : 1,
	"mixer"               : 1,
	"pudding"             : 1,
	"herd"                : 1,
	"battery"             : 1,
	"drawing"             : 1,
	"blind"               : 1,
	"mall"                : 1,
	"pesto"               : 1,
	"cage"                : 1,
	"stage"               : 1,
	"attic"               : 1,
	"hour hand"           : 0,
	"ring"                : 1,
	"hard drive"          : 1,
	"knee pad"            : 1,
	"cigar"               : 1,
	"wedding"             : 1,
	"dinosaurs"           : 0,
	"baby"                : 1,
	"lounge"              : 1,
	"speaker"             : 1,
	"comb"                : 1,
	"knife block"         : 1,
	"breakfast"           : 1,
	"chains"              : 0,
	"scarf"               : 1,
	"spice"               : 1,
	"scaffolding"         : 1,
	"marker"              : 1,
	"minute hand"         : 0,
	"sugar"               : 1,
	"face mask"           : 1,
	"casserole"           : 1,
	"turbine"             : 1,
	"snack"               : 1,
	"money"               : 0,
	"pub"                 : 0,
	"keypad"              : 1,
	"station"             : 0,
	"hay"                 : 0,
	"spear"               : 1,
	"sack"                : 1,
	"sour cream"          : 1,
	"pouch"               : 1,
	"sandal"              : 1,
	"tomato sauce"        : 1,
	"nutella"             : 1,
	"garage"              : 1,
	"touchpad"            : 1,
	"swamp"               : 1,
	"elbow pad"           : 1,
	"carriage"            : 1,
	"menu"                : 1,
	"tongue"              : 0,
	"american flag"       : 1,
	"mother"              : 1,
	"dinner"              : 1,
	"router"              : 1,
	"snow shoe"           : 1,
	"drum"                : 1,
	"console"             : 1,
	"door frame"          : 1,
	"cafe"                : 1,
	"smoothie"            : 1,
	"game"                : 0,
	"shield"              : 1,
	"dessert"             : 1,
	"football"            : 1,
	"radiator"            : 1,
	"headboard"           : 1,
	"trash"               : 1,
	"audience"            : 1,
	"vinegar"             : 1,
	"buffet"              : 1,
	"picnic"              : 1,
	"topping"             : 0,
	"lobby"               : 1,
	"tunnel"              : 1,
	"lavender"            : 1,
	"jewelry"             : 1,
	"corn"                : 1,
	"mint"                : 1,
	"fudge"               : 1,
	"decoration"          : 1,
	"daughter"            : 1,
	"whisk"               : 1,
	"bedding"             : 1,
	"wig"                 : 1,
	"cream"               : 0,
	"tea"                 : 1,
	"bomb"                : 1,
	"pasture"             : 1,
	"dryer"               : 1,
	"drink"               : 1,
	"brush"               : 1,
	"coral"               : 1,
	"pork"                : 1,
	"guacamole"           : 1,
	"marina"              : 1,
	"garnish"             : 1,
	"seal"                : 1,
	"elevator"            : 1,
	"rolling pin"         : 1,
	"wallpaper"           : 1,
	"paddle"              : 1,
	"roll"                : 1,
	"gym"                 : 0,
	"stump"               : 1,
	"porch"               : 1,
	"accessory"           : 1,
	"wings"               : 0,
	"controller"          : 1,
	"hummus"              : 0,
	"crust"               : 1,
	"shuttle"             : 1,
	"beverage"            : 1,
	"herb"                : 1,
	"vine"                : 1,
	"feeder"              : 1,
	"terminal"            : 1,
	"coin"                : 1,
	"produce"             : 0,
	"hurdle"              : 1,
	"dip"                 : 1,
	"shower"              : 1,
	"chocolate"           : 1,
	"grinder"             : 1,
	"stones"              : 0,
	"lab coat"            : 1,
	"backyard"            : 0,
	"paw"                 : 1,
	"fire"                : 1,
	"dough"               : 1,
	"harbor"              : 0,
	"figure"              : 1,
	"champagne"           : 1,
	"cat food"            : 1,
	"oatmeal"             : 1,
	"moss"                : 1,
	"patio"               : 1,
	"dog food"            : 0,
	"pantry"              : 1,
	"seafood"             : 0,
	"juice"               : 0,
	"steam"               : 0,
	"oven door"           : 1,
	"carpet"              : 1,
	"icing"               : 0,
	"bone"                : 1,
	"cooler"              : 1,
	"dumpster"            : 1,
	"cheese"              : 1,
	"stew"                : 1,
	"butter"              : 1,
	"dinosaur"            : 1,
	"salad"               : 1,
	"horse hoof"          : 1,
	"drape"               : 1,
	"athletic shoe"       : 1,
	"hedge"               : 1,
	"desert"              : 0,
	"parent"              : 1,
	"vacuum"              : 1,
	"sauce"               : 0,
	"gravy"               : 1,
	"pump"                : 1,
	"cooking oil"         : 0,
	"hook"                : 1,
	"magnet"              : 1,
	"batter"              : 0,
	"sea"                 : 0,
	"barrier"             : 1,
	"tissues"             : 0,
	"egg shell"           : 1,
	"mexican food"        : 0,
	"milk"                : 1,
	"heels"               : 0,
	"roadside"            : 0,
	"glaze"               : 0,
	"foil"                : 1,
	"sea foam"            : 1,
	"honey"               : 0,
	"liquor"              : 0,
	"dressing"            : 0,
	"armor"               : 1,
	"syrup"               : 0,
	"canopy"              : 1,
	"lipstick"            : 1,
	"wool"                : 0,
	"lip"                 : 0,
	"peanut butter"       : 1,
	"oil"                 : 0,
	"cinnamon"            : 1,
	"smoke"               : 0,
	"chinese food"        : 1,
	"stone"               : 0,
	"beef"                : 0,
	"soup"                : 0,
	"broth"               : 0,
	"powder"              : 0,
	"net"                 : 1,
	"heel"                : 1,
	"frosting"            : 0,
	"flour"               : 0,
	"rain"                : 0,
	"skin"                : 0,
	"salt"                : 0,
	"blood"               : 0,
	"alcohol"             : 0,
	"meat"                : 0,
	"liquid"              : 0
}
